version: '2'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./server:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  api-web:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306:3306"

  client-web:
    build: 
      context: .
      dockerfile: docker/client.dockerfile
    working_dir: /usr/src/app
    volumes:
        - ./my-app:/usr/src/app
        - '/usr/src/app/node_modules'
    ports:
      - 4200:80

volumes:
  dbdata: