version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/api.dockerfile
    command: composer install
    volumes:
      - ./server:/api
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  api:
    image: nginx:1.10
    volumes:
      - ./server:/api
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    links:
      - php

  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - 3306:3306

  client:
    build: 
      context: .
      dockerfile: docker/client.dockerfile
    volumes:
        - ./my-app:/usr/src/app
        - '/usr/src/app/node_modules'
    ports:
      - 4200:80

volumes:
  dbdata: